name: Terraform Website Deployment
 
on:
  push:
    branches:
      - main  # or your default branch
 
jobs:
  terraform:
    name: Deploy static site with Terraform
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0  # specify your version
 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # change based on your region
 
      - name: Initialize Terraform
        run: terraform init
 
      - name: Validate Terraform
        run: terraform validate
 
      - name: Plan Terraform
        run: terraform plan
 
      - name: Apply Terraform
        run: terraform apply -auto-approve
 
      - name: Sync website files to S3
        run: |
          aws s3 sync ./website s3://your-bucket-name --delete
 
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id YOUR_DIST_ID --paths "/*"
